export const CONTRACT_API_ERROR_CODES = {
  NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CLIENT_NOT_FOUND: 'CONTRACT_CLIENT_NOT_FOUND',
  INVALID_DATA: 'CONTRACT_INVALID_DATA',
} as const;

export type ContractApiErrorCode =
  (typeof CONTRACT_API_ERROR_CODES)[keyof typeof CONTRACT_API_ERROR_CODES];
