export const LOCATION_API_ERROR_CODES = {
  COUNTRY_NOT_FOUND: 'LOCATION_COUNTRY_NOT_FOUND',
  COUNTRY_REFERENCED: 'LOCATION_COUNTRY_REFERENCED',
  PARENT_COUNTRY_INVALID: 'LOCATION_PARENT_COUNTRY_INVALID',
  STATE_NOT_FOUND: 'LOCATION_STATE_NOT_FOUND',
  STATE_REFERENCED: 'LOCATION_STATE_REFERENCED',
  PARENT_STATE_INVALID: 'LOCATION_PARENT_STATE_INVALID',
  CITY_NOT_FOUND: 'LOCATION_CITY_NOT_FOUND',
  CITY_REFERENCED: 'LOCATION_CITY_REFERENCED',
  GEO_CITY_NOT_FOUND: 'LOCATION_GEO_CITY_NOT_FOUND',
  GEO_CITY_STATE_MISMATCH: 'LOCATION_GEO_CITY_STATE_MISMATCH',
  GEO_STATE_CODE_REQUIRED: 'LOCATION_GEO_STATE_CODE_REQUIRED',
} as const;

export type LocationApiErrorCode =
  (typeof LOCATION_API_ERROR_CODES)[keyof typeof LOCATION_API_ERROR_CODES];
