export const TICKET_API_ERROR_CODES = {
  NOT_FOUND: 'TICKET_NOT_FOUND',
  ACCESS_DENIED: 'TICKET_ACCESS_DENIED',
  INVALID_VERSION: 'TICKET_INVALID_VERSION',
  USER_NOT_FOUND: 'TICKET_USER_NOT_FOUND',
} as const;

export type TicketApiErrorCode =
  (typeof TICKET_API_ERROR_CODES)[keyof typeof TICKET_API_ERROR_CODES];
