export const CLIENT_API_ERROR_CODES = {
  NOT_FOUND: 'CLIENT_NOT_FOUND',
  CPF_ALREADY_REGISTERED: 'CLIENT_CPF_ALREADY_REGISTERED',
  CNPJ_ALREADY_REGISTERED: 'CLIENT_CNPJ_ALREADY_REGISTERED',
  DUPLICATE_DOCUMENT: 'CLIENT_DUPLICATE_DOCUMENT',
  INVALID_DATA: 'CLIENT_INVALID_DATA',
} as const;

export type ClientApiErrorCode =
  (typeof CLIENT_API_ERROR_CODES)[keyof typeof CLIENT_API_ERROR_CODES];
