export const COMMON_API_ERROR_CODES = {
  CONFLICT: 'COMMON_CONFLICT',
  DOMAIN_VALIDATION_FAILED: 'COMMON_DOMAIN_VALIDATION_FAILED',
  UNAUTHORIZED: 'COMMON_UNAUTHORIZED',
  RATE_LIMITED: 'COMMON_RATE_LIMITED',
  VALIDATION_FAILED: 'COMMON_VALIDATION_FAILED',
} as const;

export type CommonApiErrorCode =
  (typeof COMMON_API_ERROR_CODES)[keyof typeof COMMON_API_ERROR_CODES];
